In [1]:
import torch
import torch.nn as nn
import numpy as np
import os

In [16]:
# Loading binary data
path_to_local_dir = os.getcwd()
with open(f"{path_to_local_dir}/data/train.bin", 'rb') as file
    train = file.read()


<_io.BufferedReader name='/Users/m.elmasri/src/moGPT/data/train.bin'>


In [19]:
train[:10]

b'J\x17#W\x19\x00\xc6\x00\xe5 '

In [21]:
from constants import BLOCK_SIZE, BATCH_SIZE
print(f"block size: {BLOCK_SIZE}, batch size: {BATCH_SIZE}")

block size: 4, batch size: 8


In [22]:
len(train) - BLOCK_SIZE

603928

In [23]:
ix = torch.randint(len(train) - BLOCK_SIZE, (BATCH_SIZE,))

In [24]:
ix

tensor([198863, 405154,  88998, 521762, 175796, 336810, 497142,  50821])

In [26]:
x = torch.stack([torch.from_numpy((train[i:i+BLOCK_SIZE])) for i in ix])

TypeError: expected np.ndarray (got bytes)

In [27]:
[torch.from_numpy((train[i:i+BLOCK_SIZE])) for i in ix]

TypeError: expected np.ndarray (got bytes)

In [5]:
from train import get_batch

In [6]:
get_batch('train')

tensor([[  301, 14210,   407,  2121],
        [ 1309,  8028,   290,  4736],
        [  683,   345,   466, 31651],
        [ 1537,    11,  1560,   502],
        [ 1677,    40,  2937,    25],
        [   25,   198, 16773,    11],
        [   13,   198,   198,    35],
        [  198,  1890, 10013,   534]])


(tensor([[  301, 14210,   407,  2121],
         [ 1309,  8028,   290,  4736],
         [  683,   345,   466, 31651],
         [ 1537,    11,  1560,   502],
         [ 1677,    40,  2937,    25],
         [   25,   198, 16773,    11],
         [   13,   198,   198,    35],
         [  198,  1890, 10013,   534]]),
 tensor([[14210,   407,  2121,   503],
         [ 8028,   290,  4736,   307],
         [  345,   466, 31651,   502],
         [   11,  1560,   502,    11],
         [   40,  2937,    25,   198],
         [  198, 16773,    11,  1282],
         [  198,   198,    35,    52],
         [ 1890, 10013,   534,  1029]]))